services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=db'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
    volumes:
      - 'mongodb:/data/db'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  client:
    image: htilssu/trungtamthethao:client
    build:
      context: ./Client
      dockerfile: Dockerfile
  spring:
    image: htilssu/trungtamthethao:spring
    build:
      context: ./Spring
      dockerfile: Dockerfile

volumes:
  mongodb:
  postgres:
networks:
  tdtt:
    driver: bridge