services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=db'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb:/data/db'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    expose:
#      - '8080:8080'
#    environment:
#      - 'DATABASE_URL=postgres://admin:admin@postgres:5432/db'
#      - 'MONGO_URL=mongodb://admin:admin@mongodb:27017/db'
#      - 'DATABASE_USERNAME=admin'
#      - 'DATABASE_PASSWORD=admin'
volumes:
  mongodb:
  postgres:
