ALTER TABLE equipment_type
DROP COLUMN IF EXISTS amount;
ALTER TABLE coach
ADD COLUMN phone_number VARCHAR(10),
ADD COLUMN name VARCHAR(100);

ALTER TABLE equipment
ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS amount INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION;
CREATE SEQUENCE IF NOT EXISTS coach_seq START WITH 1 INCREMENT BY 1;