ALTER TABLE equipment_type
DROP COLUMN IF EXISTS amount;

ALTER TABLE equipment
ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS amount INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION;